#!/bin/sh
# ck-system-restart

SHUTDOWN_CMD=shutdown
SHUTDOWN_CMD_ARGS='-r now'

# Check based on init
if [ "$(ps -p 1 -o comm=)" = openrc-init ]; then
	SHUTDOWN_CMD=openrc-shutdown
elif [ "$(ps -p 1 -o comm=)" = runit-init ]; then
	SHUTDOWN_CMD=runit-init
	SHUTDOWN_CMD_ARGS="6"
fi

if [ -x "/sbin/${SHUTDOWN_CMD}" ] ; then
	/sbin/${SHUTDOWN_CMD} ${SHUTDOWN_CMD_ARGS}
	exit $?
elif [ -x "/usr/sbin/${SHUTDOWN_CMD}" ] ; then
	/usr/sbin/${SHUTDOWN_CMD} ${SHUTDOWN_CMD_ARGS}
	exit $?
else
	exit 1
fi
