#!/bin/sh
# ck-system-restart

SHUTDOWN_CMD=shutdown
SHUTDOWN_CMD_ARGS='-r now'

# Check based on init
case "$(ps -p 1 -o comm=)" in
	openrc-init)
		SHUTDOWN_CMD=openrc-shutdown
		SHUTDOWN_CMD_ARGS='-r now'
	;;
	runit)
		SHUTDOWN_CMD=runit-init
		SHUTDOWN_CMD_ARGS="6"
	;;
	*)
		SHUTDOWN_CMD=shutdown
		SHUTDOWN_CMD_ARGS='-r now'
	;;
esac

if [ -x "/sbin/${SHUTDOWN_CMD}" ] ; then
	/sbin/${SHUTDOWN_CMD} ${SHUTDOWN_CMD_ARGS}
	exit $?
elif [ -x "/usr/sbin/${SHUTDOWN_CMD}" ] ; then
	/usr/sbin/${SHUTDOWN_CMD} ${SHUTDOWN_CMD_ARGS}
	exit $?
else
	exit 1
fi
