#!/bin/sh

DIST_BIN=`dirname "$0"`

cd ${DIST_BIN}
cd ../xml
../tools/spec-to-docbook ../spec/*.xml
if [ $? -ne 0 ]; then
    exit 1
fi

cd ../../src
../doc/tools/spec-strip-docs ../doc/spec/*.xml
if [ $? -ne 0 ]; then
    exit 1
fi

for name in session seat manager; do
    mv ck-${name}-no-docs.xml ck-${name}.xml
    if [ $? -ne 0 ]; then
        exit 1
    fi
done

exit 0
